version: '3.8'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
            POSTGRES_USER: '${DATABASE_USER}'
            POSTGRES_DB: '${DATABASE_NAME}'
            DATABASE_PORT: '5432'
        ports:
            - '5432:5432'
        env_file: .env
    backend:
        depends_on:
            - 'db'
        build: .
        ports:
            - '3333:3333'
        hostname: web
        environment:
            DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
            DATABASE_USER: '${DATABASE_USER}'
            DATABASE_NAME: '${DATABASE_NAME}'
            DATABASE_PORT: '5432'
            DATABASE_HOST: db
        volumes:
            - '.:/app'
volumes:
    db:

networks:
    default:
